- name: Repository is present
  apt_repository:
    repo: ppa:openjdk-r/ppa
  tags: [java]

- name: Package is present
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  tags: [java]
