- name: Container is running
  docker_container:
    name: elasticsearch
    image: elasticsearch:2
    state: started
    ports:
      - 9200:9200
    volumes:
      /data/elasticsearch:/usr/share/elasticsearch/data
  tags: [elasticsearch]
